Header header
#object pose relative to header frame
geometry_msgs/Pose objectPose
float32 object_radius
float32 object_height
---
float32 minD
float32 maxD
float32 minA
float32 maxA
float32 minH
float32 maxH
