#encodes the frame id of the object
Header header
#frame_id for the approach vector
string approach_frame
#only configurations aligned with this vector will be considered
float32[3] approach_vector
#maximum angle against this vector. >0 means in the same hyperplane
float32 approach_angle
#object pose relative to header frame
geometry_msgs/Pose objectPose
#object radius
float32 object_radius
#for cylindrical primitives only
float32 object_height
---
string frame_id
hiqp_msgs/Primitive[] constraints
float32 min_oa
float32 max_oa
float32 volume
float32 time
bool success
